version: "3"
services:
  postgres:
    image: postgres:11
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/tmp
    networks:
      - default
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    # restart: always
    ports:
    - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@mvb.com'
      PGADMIN_DEFAULT_PASSWORD: '1234'
    networks:
      - default

networks:
  default:
      driver: bridge

volumes:
  postgres-data: